### ISSUE TITLE
[Feature request] Опция "нормализации"/масштабирования в Basic stats

### ISSUE THREAD

**Issue by LSinev** [SergeyShk/ruTS#7]
Предлагаю добавить опцию представления в нормализованных/относительных величинах большей части статистик из набора BasicStats(). Все количества слов, кроме общего числа слов делить на это общее число слов. Аналогично со знаками.
`c_letters`, `c_syllables`, `n_complex_words`, `n_monosyllable_words`, `n_polysyllable_words`, `n_long_words`, `n_simple_words`, `n_unique_words` делить/нормировать на `n_words`.
`n_letters`, `n_punctuations`, `n_spaces` делить/нормировать на `n_chars`.
Удобнее не самому делить, а сразу получать в выдаче.

**Comment by SergeyShk** [comment]
Спасибо. Взял в работу.

**Comment by SergeyShk** [comment]
6e5a3eb

**Comment by SergeyShk** [comment]
> Предлагаю добавить опцию представления в нормализованных/относительных величинах большей части статистик из набора BasicStats(). Все количества слов, кроме общего числа слов делить на это общее число слов. Аналогично со знаками.
> `c_letters`, `c_syllables`, `n_complex_words`, `n_monosyllable_words`, `n_polysyllable_words`, `n_long_words`, `n_simple_words`, `n_unique_words` делить/нормировать на `n_words`.
> `n_letters`, `n_punctuations`, `n_spaces` делить/нормировать на `n_chars`.
> Удобнее не самому делить, а сразу получать в выдаче.
